name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Test
        run: make test
      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Format
        run: make fmt && git diff --exit-code --quiet -- '*.go'
      - name: Vet
        run: make vet
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
          args: --timeout=5m
